### ISSUE TITLE
Missing Markov_Risk_Calc and dataset

### ISSUE THREAD

**Issue by ramoncodes-collab** [koo-ec/SafeDrones#1]
Hey,
I am interested in your repo @koo-ec , but couldn't use the implementation. Markov_Risk_Calc() seems to be missing? Also, your method seems to use a drone dataset- Would it be possible share it?

Thank you

**Comment by koo-ec** [comment]
Hello,

Thank you for your interest and also for your comment. I will soon upload the mentioned function.

**Comment by koo-ec** [comment]
@ramoncodes-collab, 

Sorry for the delay. The first version of the Markov_Risk_Calc() function is now available.

Regards
